apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-ghost-pv
  namespace: gh
spec:
  capacity:
   storage: 20Gi
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /nas/db
    server: 192.168.1.85
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-ghost-pvc
  namespace: gh
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: mysql-ghost-pv
