apiVersion: v1
kind: Service
metadata:
  name: ghost-db
  namespace: gh
spec:
  type: ClusterIP
  selector:
    app: ghost-db
  ports:
    - port: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-db
  namespace: gh
  labels:
    app: ghost-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-db
  template:
    metadata:
      labels:
        app: ghost-db
    spec:
      containers:
      - name: con-ghost-db
        image: mysql:8.0
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        volumeMounts:
        - name: mysql-pvc-deploy
          mountPath: "/var/lib/mysql"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ghost
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "756Mi"
            cpu: "600m"
      volumes:
      - name: mysql-pvc-deploy
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: gh
spec:
  capacity:
   storage: 20Gi
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /nas
    server: 192.168.1.85
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: gh
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: mysql-pv