apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-db
  namespace: gh
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: con-ghost-db
        image: mysql
        volumeMounts:
        - name: mysql-pvc-deploy
          path: "/var/lib/mysql"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: db
        - name: MYSQL_USER
          valueFrom:
            name: ghostdb
            value: USER_NAME
        - name: MYSQL_PASSWORD
          valueFrom:
            name: ghostdb
            value: PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
    volumes:
    - name: mysql-pvc-deploy
      persistentVolumeClaim:
        claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: gh
  label:
    pv: mysql-gh
spec:
  capacity:
   storage: 5Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: "/mnt/hgfs/mysql-ghost/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: gh
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: slow
  selector:
    matchLabels:
      pv: mysql-gh
