apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: gh
spec:
  type: ClusterIP
  selector:
    app: ghost
  ports:
    - name: ghostport
      protocol: TCP
      port: 2368
      targetPort: 2368
---
apiVersion: v1
kind: Secret
metadata:
  name: ghostdb
  namespace: gh
type: Opaque
data:
  USER_NAME: cm9vdA==
  PASSWORD: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: gh
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: con-ghost
        image: ghost:4
        volumeMounts:
        - name: ghost-pvc-deploy
          mountPath: "/var/lib/ghost/current/content"
        ports:
        - containerPort: 2368
        env:
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: ghost-db.gh
        - name: database__connection__user
          value: root
 #         valueFrom:
 #           secretKeyRef:
 #             name: ghostdb
 #             key: USER_NAME
        - name: database__connection__password
          value: ghost
#          valueFrom:
#            secretKeyRef:
#              name: ghostdb
#              key: PASSWORD
        - name: database__connection__database
          value: ghost
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
      volumes:
      - name: ghost-pvc-deploy
        persistentVolumeClaim:
          claimName: ghost-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
  namespace: gh
spec:
  capacity:
   storage: 2Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /nas
    server: 192.168.1.85
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: gh
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
  volumeName: ghost-pv

